# Документ использует T2A + inputenc, поэтому собирается именно pdflatex,
# а не xelatex/lualatex.
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$out_dir  = 'build';
$clean_ext = 'synctex.gz run.xml bbl';
